### PR TITLE
Dataloader docs

### PR DESCRIPTION
**Pull request by mzouink**

### CODE REVIEW

**Comment by mzouink** [comment]
Result : [Creating a CellMap Data PyTorch Dataloader — CellMap Segmentation Challenge.pdf](https://github.com/user-attachments/files/18131292/Creating.a.CellMap.Data.PyTorch.Dataloader.CellMap.Segmentation.Challenge.pdf)

**Comment by mzouink** [comment]
waiting for @davidackerman to update the csv then + feedbacks @rhoadesScholar

**Comment by rhoadesScholar** [comment]
looking great! could you add a bit about the `make_datasplit_csv` helper function? you specify what classes/crops you want and it makes the csv for you by looking at the data you have stored. also has the option to use s3

**Comment by mzouink** [comment]
csvs are updated and ready for review

**Review by rhoadesScholar — APPROVED** [review]

**Comment by rhoadesScholar** [comment]
@mzouink did you get the `make_datasplit_csv` in the docs? asking for a friend.

**Pull request merged**
